{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-dummuy-service.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "k8s-dummuy-service.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ required "Port is required" .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
{{- end }}
