name: release
on:
 push:
   branches:
     - main
jobs:
  build:
    uses: ahmdelemam/svc-ci-bootstrap/.github/workflows/resuable-build-chart.yaml@main
    with:
      service_name: ${{ github.event.repository.name }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      name: Checkout
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: create env branch
      shell: bash
      run: |
        git checkout --orphan env/prod  && git rm -rf . || git swich env/prod
        git pull --set-upstream origin env/prod || true
        rm -rf charts
        rm -rf application


    - uses: actions/download-artifact@v4
      with:
        name: charts
        path: charts

    - name: generate argocd application
      shell: bash
      env:
        APP_NAME: ${{ github.event.repository.name }}
        REPO_NAME: ${{ github.event.repository.name }}
        NAMESPACE: ${{ github.event.repository.name }}
      run: |
        mkdir -p application
        cat << EOF > application/argocd.tpl
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: ${APP_NAME}
          namespace: argocd
          finalizers:
          - resources-finalizer.argocd.argoproj.io
        spec:
          destination:
            namespace: ${NAMESPACE}
            server: https://kubernetes.default.svc
          project: default
          source:
            path: charts
            repoURL: https://github.com/mohamedragab2024/${REPO_NAME}.git
            targetRevision: env/prod
            helm:
              valueFiles:
                - values-live.yaml
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
              allowEmpty: true
            syncOptions:
              - CreateNamespace=true
        EOF
        envsubst < application/argocd.tpl > application/${APP_NAME}-argocd-app.yaml
        rm -f application/argocd.tpl

    - name: publish charts
      shell: bash
      run: |
        git config --global user.email "m.ragab6010@gmail.com"
        git config --global user.name "mohamedragab2024"
        git add .
        git commit -m "Create a new version" || true
        git push --set-upstream origin env/prod || true
 
  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
    - uses: actions/checkout@v4
      name: Checkout
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: env/prod
    - name: Setup ArgoCD CLI
      shell: bash
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v2.10.0/argocd-linux-amd64
        chmod +x argocd-linux-amd64
        sudo mv argocd-linux-amd64 /usr/local/bin/argocd   
    - name: Create ArgoCD application
      shell: bash
      run: |
        argocd login 212.2.242.173 --username admin --password 5GYhiX9Op0g3AX5t --insecure --grpc-web
        argocd app create -f application/${{github.event.repository.name}}-argocd-app.yaml || true
    - name: Sync ArgoCD application
      shell: bash
      run: |
        argocd app sync ${{ github.event.repository.name }}

        





    