name: release
on:
 push:
   branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - name: create env branch
      shell: bash
      run: |
        git checkout --orphan env/prod  && git rm -rf . || git swich env/prod
        git pull --set-upstream origin env/prod || true
        
    - name: clone base charts
      shell: bash
      env:
        USERNAME: mohamedragab2024
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config --global user.email "m.ragab6010@gmail.com"
        git config --global user.name "mohamedragab2024"
        git clone https://${USERNAME}:${ACCESS_TOKEN}@github.com/mohamedragab2024/k8s-lessons.git
        cp -r k8s-lessons/charts/* charts/
        git commit -m "Create a new version"
        git push origin env/prod
    





    