name: release
on:
 push:
   branches:
     - main
jobs:
  build-publish-charts:
    uses: ahmdelemam/svc-ci-bootstrap/.github/workflows/resuable-build-chart.yaml@main
    with:
      service_name: ${{ github.event.repository.name }}
      namespace: ${{ github.event.repository.name }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

        





    